name: {{name}}
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  mocktail: ^1.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env.development
    - .env.production
